---

- name: Determine latest version
  uri:
    url: https://api.github.com/repos/hetznercloud/cli/releases/latest
  register: latest

- debug:
    msg: "Installing hcloud {{ latest.json.tag_name }}"

- name: Download and install
  unarchive:
    src: https://github.com/hetznercloud/cli/releases/download/{{ latest.json.tag_name }}/hcloud-linux-amd64-{{ latest.json.tag_name }}.tar.gz
    dest: ~/.local/bin/
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
      - "--wildcards hcloud-linux-amd64-{{ latest.json.tag_name }}/bin/* hcloud-linux-amd64-{{ latest.json.tag_name }}/etc/hcloud.bash_completion.sh"

- name: Install bash completion
  command: mv ~/.local/etc/hcloud.bash_completion.sh ~/.local/etc/bash_completion.d/hcloud
