---

- name: Determine latest version
  uri:
    url: https://api.github.com/repos/rancher/cli/releases/latest
  register: latest

- debug:
    msg: "Installing rancher-cli {{ latest.json.tag_name }}"

- name: Download and install
  unarchive:
    src: https://github.com/rancher/cli/releases/download/{{ latest.json.tag_name }}/rancher-linux-amd64-{{ latest.json.tag_name }}.tar.gz
    dest: ~/.local/bin/
    remote_src: yes
    extra_opts: ['--strip-components=1']
