tap "homebrew/aliases"
tap "linuxbrew/fonts"

tap "nicholasdille/tap"
tap "nicholasdille/immortal"
tap "claui/whence"
tap "gergelyrozsas/systemctl"
tap "filippo.io/age"
tap "dagger/tap"
tap "cuelang/tap"

brew "powerline-go"
brew "font-cascadia-code"
brew "font-cascadia-code-pl"
brew "font-cascadia-mono"
brew "font-cascadia-mono-pl"
brew "whalebrew"

brew "age"
brew "mkcert"
brew "dagger"
brew "cue"

brew "doitlive"

brew "cowsay"
brew "ponysay"
brew "lolcat"
brew "figlet"
brew "toilet"
