---

- name: Determine latest version
  uri:
    url: https://api.github.com/repos/mayflower/docker-ls/releases/latest
  register: latest

- debug:
    msg: "Installing docker-ls/docker-rm {{ latest.json.tag_name }}"

- name: Download and install
  unarchive:
    src: https://github.com/mayflower/docker-ls/releases/download/{{ latest.json.tag_name }}/docker-ls-linux-amd64.zip
    dest: ~/.local/bin/
    remote_src: yes
