---

- name: Determine latest version
  shell: curl --silent https://api.github.com/repos/docker/app/releases | jq --raw-output '.[] | select(.prerelease == true) | .tag_name' | sort -V -r | head -1
  register: latest

- debug:
    msg: "Installing docker-app {{ latest.stdout }}"

- name: Download and install
  unarchive:
    src: https://github.com/docker/app/releases/download/{{ latest.stdout }}/docker-app-linux.tar.gz
    dest: ~/.local/bin/
    remote_src: yes

- name: Rename binary
  command: mv ~/.local/bin/docker-app-linux ~/.local/bin/docker-app
