"$schema" = 'https://starship.rs/config-schema.json'

format = """\
[](fg:240)\
$username\
$directory\
$git_branch\
$git_status\
$kubernetes\
$status\
[ ](bg:bright-black)[](fg:bright-black) \
"""

[username]
disabled = false
show_always = true
format = "[$user ]($style)"
style_user = "fg:250 bg:240"
style_root = "bg:124"

[directory]
disabled = false
truncation_length = 1
truncation_symbol = "󰇘/"
format = "[ $path ]($style)" #
style = "fg:15 bg:237"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:black bg:yellow"

[git_status]
format = '($ahead_behind)[( $all_status )]($style)'
style = "fg:15 bg:130"
# ahead_behind:
conflicted = "" #"!"
ahead = "[( ${count}⇡ )](fg:15 bg:130)"
behind = "[( ${count}⇣ )](fg:15 bg:130)"
diverged = "[( X⇡${ahead_count}⇣${behind_count} )](fg:15 bg:130)" #"V" #"󰓁"
up_to_date = "[  ](fg:black bg:bright-green)"
# all_status:
untracked = "${count}?"
stashed = "${count}_"
modified = "${count}~"
deleted = "${count}-"
renamed = "${count}>"
staged = "${count}^"

[kubernetes]
disabled = false
symbol = "⎈"
format = '[ $symbol $context ](fg:117 bg:21)[ $namespace ](fg:117 bg:26)'
style = ""

[character]
success_symbol = '[ ](bg:bright-black)'
error_symbol = '[ ✗](fg:bright-red bg:bright-black)'

[status]
disabled = false
format = '[ ! $status ]($style)'
map_signal = true
style = "fg:15 bg:161"

