---

- name: Determine latest version
  uri:
    url: https://api.github.com/repos/JonasProgrammer/docker-machine-driver-hetzner/releases/latest
  register: latest

- debug:
    msg: "Installing docker-machine-driver-hetzner {{ latest.json.tag_name }}"

- name: Download and install
  unarchive:
    src: https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/{{ latest.json.tag_name }}/docker-machine-driver-hetzner_{{ latest.json.tag_name }}_linux_amd64.tar.gz
    dest: ~/.local/bin/
    remote_src: yes
