---

- name: Determine latest version
  uri:
    url: https://api.github.com/repos/helm/helm/releases/latest
  register: latest

- debug:
    msg: "Installing helm {{ latest.json.tag_name }}"

- name: Download and install
  unarchive:
    src: https://storage.googleapis.com/kubernetes-helm/helm-{{ latest.json.tag_name }}-linux-amd64.tar.gz
    dest: ~/.local/bin/
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: Initialize helm
  command: helm init --client-only
  args:
    creates: ~/.helm

- name: Install tillerless plugin
  command: "helm plugin install {{ item }}"
  args:
    creates: ~/.helm/cache/plugins/{{ item | regex_replace('/', '-') }}/
  with_items:
    - https://github.com/rimusz/helm-tiller
    - https://github.com/adamreese/helm-local
